baseURL = "https://eightsuzuki.github.io/"
languageCode = 'en-us'
subtitle = "Exploring the World of Technology"
title = "suzuki8"
theme = "hugo-bearblog"


author = "Eight Suzuki"
copyright = "Copyright Â© 2020, EightSuzuki."

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  description = "Eight Suzuki"
  favicon = "/images/favicon.ico"
  images = ["images/share.png"]

  title = "Eight Suzuki Site"

[params.header]
  showTitle = true
  showSubtitle = true
  showDescription = true
  showLogo = true
  showNavigation = true
  showSearchIcon = true
